name: Release MacOS

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  localize:
    uses: ./.github/workflows/shared-steps.yml
    with:
      run_on: macos-15  # arm64
      platform: macos
      version_command: |
        curl -L -o Termius.dmg https://termi.us/mac-download || { echo "::error::Failed to download Termius.dmg"; exit 1; }
        temp_mount_point=$(mktemp -d)
        hdiutil attach Termius.dmg -mountpoint "$temp_mount_point" -quiet -nobrowse || { echo "::error::Failed to mount Termius.dmg"; exit 1; }
        termius_app_path="$temp_mount_point/Termius.app"
        if [ ! -d "$termius_app_path" ]; then
          echo "::error::Termius.app not found"
          exit 1
        fi
        info_plist_path="$termius_app_path/Contents/Info.plist"
        if [ -f "$info_plist_path" ]; then
          termius_version=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" "$info_plist_path")
          if [ -n "$termius_version" ]; then
            echo "Termius version: $termius_version"
            echo "TERMIUS_VERSION=$termius_version" >> $GITHUB_ENV
          else
            echo "::error::Failed to get version from Info.plist"
            exit 1
          fi
        else
          echo "::error::Info.plist not found"
          exit 1
        fi
        hdiutil detach "$temp_mount_point" -quiet || echo "::warning::Failed to unmount Termius.dmg"
        rm -rf "$temp_mount_point"
      install_command: |
        temp_mount_point=$(mktemp -d)
        hdiutil attach Termius.dmg -mountpoint "$temp_mount_point" -quiet -nobrowse || { echo "::error::Failed to mount Termius.dmg"; exit 1; }
        termius_app_path=$(find "$temp_mount_point" -name "Termius.app" -type d -maxdepth 3)
        if [ -z "$termius_app_path" ]; then
          echo "::error::Termius.app not found"
          exit 1
        fi
        cp -R "$termius_app_path" /Applications/ || { echo "::error::Failed to install Termius.app"; exit 1; }
        hdiutil detach "$temp_mount_point" -quiet || echo "::warning::Failed to unmount Termius.dmg"
        rm -rf "$temp_mount_point"
        sudo chmod -R 755 /Applications/Termius.app/Contents/Resources
      source_path: /Applications/Termius.app/Contents/Resources/app.asar